@@include('../libs/jquery-3.4.1.js')
@@include('../libs/swiper.min.js')
@@include('../libs/gsap.min.js')
@@include('../libs/scrollmagic.min.js')
@@include('../libs/scrollTrigger.min.js')
@@include('../libs/animation.gsap.min.js')
@@include('../libs/rellax.min.js')
